spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/security?useTimezone=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
hystrix:
  shareSecurityContext: true
